# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3.xci
# IP: The module: 'ublaze_system_microblaze_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3.xci
# IP: The module: 'ublaze_system_microblaze_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
