# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0.xci
# IP: The module: 'ublaze_system_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.srcs/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0.xci
# IP: The module: 'ublaze_system_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ublaze_system_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
