# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/ublaze_system/ublaze_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system || ORIG_REF_NAME==ublaze_system} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_clk_wiz_0_0/ublaze_system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_clk_wiz_0_0 || ORIG_REF_NAME==ublaze_system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_microblaze_0_3/ublaze_system_microblaze_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_microblaze_0_3 || ORIG_REF_NAME==ublaze_system_microblaze_0_3} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_dlmb_v10_0/ublaze_system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_dlmb_v10_0 || ORIG_REF_NAME==ublaze_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_ilmb_v10_0/ublaze_system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_ilmb_v10_0 || ORIG_REF_NAME==ublaze_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_dlmb_bram_if_cntlr_0/ublaze_system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ublaze_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_ilmb_bram_if_cntlr_0/ublaze_system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ublaze_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_lmb_bram_0/ublaze_system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_lmb_bram_0 || ORIG_REF_NAME==ublaze_system_lmb_bram_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_xbar_0/ublaze_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_xbar_0 || ORIG_REF_NAME==ublaze_system_xbar_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_periph_0/ublaze_system_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ublaze_system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_microblaze_0_axi_intc_0/ublaze_system_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==ublaze_system_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_mdm_1_0/ublaze_system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_mdm_1_0 || ORIG_REF_NAME==ublaze_system_mdm_1_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_rst_clk_wiz_0_100M_0/ublaze_system_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==ublaze_system_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_axi_gpio_0_1/ublaze_system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_axi_gpio_0_1 || ORIG_REF_NAME==ublaze_system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_axi_gpio_1_1/ublaze_system_axi_gpio_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_axi_gpio_1_1 || ORIG_REF_NAME==ublaze_system_axi_gpio_1_1} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_axi_gpio_2_0/ublaze_system_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_axi_gpio_2_0 || ORIG_REF_NAME==ublaze_system_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_axi_uartlite_0_1/ublaze_system_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_axi_uartlite_0_1 || ORIG_REF_NAME==ublaze_system_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_axi_timer_0_0/ublaze_system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_axi_timer_0_0 || ORIG_REF_NAME==ublaze_system_axi_timer_0_0} -quiet] -quiet

# IP: bd/ublaze_system/ip/ublaze_system_Seg7IP_0_2/ublaze_system_Seg7IP_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ublaze_system_Seg7IP_0_2 || ORIG_REF_NAME==ublaze_system_Seg7IP_0_2} -quiet] -quiet

# XDC: c:/Workspace/TP_SOC_IP/TP_ublaze_3DN/TP_ublaze_3DN.gen/sources_1/bd/ublaze_system/ublaze_system_ooc.xdc
